services:
  http:
    image: nginx:1.20
    restart: always
    ports:
      - '80:80'
    volumes:
      - './:/app/'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile-production
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    restart: always
    volumes:
      - '.:/app/'
    networks:
      - laravel
    depends_on:
      - pgsql
  node:
    image: node:16
    volumes:
        - './:/app/'
    working_dir: '/app/'
  pgsql:
    image: postgres:14
    restart: always
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE:-laravel}'
      POSTGRES_USER: '${DB_USERNAME:-laravel}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE:-laravel}", "-U", "${DB_USERNAME:-laravel}" ]
networks:
  laravel:
    driver: bridge
volumes:
  pgsql:
    driver: local
