services:
  http:
    image: nginx:1.20
    ports:
      - "80:80"
    volumes:
      - './:/app/'
      - './docker/nginx/nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile-production
      args:
        WWWUSER: 'laravel'
        WWWUID: '1000'
    volumes:
      - '.:/app/'
    networks:
      - laravel
    depends_on:
      - pgsql
  node:
    image: node:16
    volumes:
        - './:/app/'
    working_dir: '/app/'
  pgsql:
    image: 'postgres:13'
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]
networks:
  laravel:
    driver: bridge
volumes:
  pgsql:
    driver: local
  redis:
    driver: local
